<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX9bxl2n\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX9bxl2n/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerX9bxl2n.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerX9bxl2n\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerX9bxl2n\appDevDebugProjectContainer(array(
    'container.build_hash' => 'X9bxl2n',
    'container.build_id' => '8129bf69',
    'container.build_time' => 1534025462,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerX9bxl2n');
